In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [5]:
a = np.array([[1, 2], [3, 4]])

In [6]:
a

array([[1, 2],
       [3, 4]])

In [11]:
a = np.array([1, 2, 3, 4, 5], ndmin = 1)

In [12]:
a

array([1, 2, 3, 4, 5])

In [13]:
a = np.array([1, 2, 3], dtype = complex)

In [14]:
a

array([1.+0.j, 2.+0.j, 3.+0.j])