# 逻辑运算

In [2]:
import numpy as np

In [3]:
score = np.random.randint(40,100,(10,5))

In [4]:
score

array([[70, 61, 41, 71, 94],
       [79, 99, 82, 48, 66],
       [78, 49, 53, 75, 56],
       [98, 67, 64, 99, 51],
       [84, 45, 86, 59, 94],
       [52, 51, 57, 45, 41],
       [86, 83, 94, 65, 45],
       [56, 70, 57, 87, 72],
       [44, 67, 98, 59, 90],
       [63, 74, 88, 67, 59]])

In [5]:
test_score = score[6:,0:5]

In [6]:
test_score

array([[86, 83, 94, 65, 45],
       [56, 70, 57, 87, 72],
       [44, 67, 98, 59, 90],
       [63, 74, 88, 67, 59]])

In [7]:
test_score > 60

array([[ True,  True,  True,  True, False],
       [False,  True, False,  True,  True],
       [False,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])

In [8]:
test_score[test_score>60] = 1

In [9]:
test_score

array([[ 1,  1,  1,  1, 45],
       [56,  1, 57,  1,  1],
       [44,  1,  1, 59,  1],
       [ 1,  1,  1,  1, 59]])